# Generated by Django 4.1.6 on 2023-02-16 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_prouduc_prouduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='prouduct',
            name='image_url',
        ),
        migrations.AddField(
            model_name='prouduct',
            name='image',
            field=models.FileField(null=True, upload_to='static/uploads'),
        ),
        migrations.AddField(
            model_name='prouduct',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.category'),
        ),
    ]
