# Generated by Django 4.1.6 on 2023-02-20 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category_remove_prouduct_image_url_prouduct_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='prouduct',
            name='product_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
